# Generated by Django 4.2.27 on 2026-01-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido_Paterno', models.CharField(max_length=50)),
                ('Apellido_Materno', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo_electronico', models.EmailField(max_length=150, unique=True)),
                ('Contrasena', models.CharField(max_length=255)),
                ('Tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('General', 'General')], default='General', max_length=20)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
