# Generated by Django 4.2.27 on 2026-01-27 19:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="creado_en",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="nombre",
        ),

        # ✅ COORDENADAS: aquí sí tiene sentido un default tipo "0,0"
        migrations.AddField(
            model_name="proyecto",
            name="Coordenadas",
            field=models.CharField(default="0,0", max_length=50),
            preserve_default=False,
        ),

        # ✅ DIRECCIÓN: aquí sí tiene sentido un texto tipo "SIN DEFINIR"
        migrations.AddField(
            model_name="proyecto",
            name="Direccion",
            field=models.CharField(default="SIN DEFINIR", max_length=255),
            preserve_default=False,
        ),

        # ✅ FK: default=1 SOLO sirve para rellenar registros viejos (si existieran)
        migrations.AddField(
            model_name="proyecto",
            name="ID_Usuario",
            field=models.ForeignKey(
                db_column="ID_Usuario",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyectos",
                to="core.usuario",
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="proyecto",
            name="Nombre_Empresa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        migrations.AddField(
            model_name="proyecto",
            name="Nombre_Proyecto",
            field=models.CharField(default="PROYECTO_SIN_NOMBRE", max_length=100),
            preserve_default=False,
        ),

        # ✅ Importante: entero (sin comillas)
        migrations.AddField(
            model_name="proyecto",
            name="Numero_Fases",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="proyecto",
            name="Voltaje_Nominal",
            field=models.CharField(default="0", max_length=20),
            preserve_default=False,
        ),

        migrations.AlterModelTable(
            name="proyecto",
            table="proyectos",
        ),
    ]
