# Generated by Django 4.2.27 on 2026-02-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_proyecto_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_key', models.CharField(max_length=150, unique=True)),
                ('fails', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_locks',
            },
        ),
    ]
