# Generated by Django 4.2.27 on 2026-02-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loginlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=150)),
                ('actor_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(max_length=60)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('target_model', models.CharField(blank=True, default='', max_length=60)),
                ('target_id', models.CharField(blank=True, default='', max_length=60)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
