# Generated by Django 4.2.27 on 2026-02-12 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_tipo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_log',
        ),
    ]
