# Generated by Django 4.2.27 on 2026-02-21 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irradiancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('tarifa', models.CharField(blank=True, default='', max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('estado', models.CharField(blank=True, default='', max_length=60)),
                ('ciudad', models.CharField(max_length=80)),
                ('ene', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('abr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('jun', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('jul', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ago', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sep', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('oct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nov', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dic', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Irradiancia',
                'verbose_name_plural': 'Irradiancias',
                'ordering': ['estado', 'ciudad'],
            },
        ),
        migrations.CreateModel(
            name='NumeroPaneles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_facturacion', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral')], max_length=10)),
                ('eficiencia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('consumos', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('irradiancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculos_numero_paneles', to='core.irradiancia')),
            ],
            options={
                'verbose_name': 'Cálculo número de paneles',
                'verbose_name_plural': 'Cálculos número de paneles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanelSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modulo', models.IntegerField(unique=True)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('potencia', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('voc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('isc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vmp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('imp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('module_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Panel Solar',
                'verbose_name_plural': 'Paneles Solares',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoPaneles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_modulos', models.IntegerField(blank=True, null=True)),
                ('generacion_por_periodo', models.JSONField(blank=True, default=dict)),
                ('generacion_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grafica_1', models.JSONField(blank=True, default=dict)),
                ('grafica_2', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_paneles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='core.numeropaneles')),
            ],
            options={
                'verbose_name': 'Resultado cálculo paneles',
                'verbose_name_plural': 'Resultados cálculo paneles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='numeropaneles',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculos_numero_paneles', to='core.panelsolar'),
        ),
        migrations.AddField(
            model_name='numeropaneles',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numero_paneles', to='core.proyecto'),
        ),
    ]
