# Generated by Django 4.2.27 on 2026-02-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_irradiancia_numeropaneles_panelsolar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelsolar',
            name='module_efficiency',
        ),
    ]
