# Generated by Django 4.2.27 on 2026-02-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_panelsolar_module_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeropaneles',
            name='consumos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='resultadopaneles',
            name='generacion_anual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
