# Generated by Django 4.2.27 on 2026-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_numeropaneles_consumos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadopaneles',
            name='potencia_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
