# Generated by Django 4.2.27 on 2026-02-23 05:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_resultadopaneles_potencia_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('potencia_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voltaje_salida', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Inversor',
                'verbose_name_plural': 'Inversores',
                'db_table': 'inversores',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='MicroInversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('potencia_w', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('canales', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Micro inversor',
                'verbose_name_plural': 'Micro inversores',
                'db_table': 'micro_inversores',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Dimensionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inversor', models.CharField(choices=[('INVERSOR', 'Inversor'), ('MICRO', 'Micro inversor')], max_length=10)),
                ('no_inversores', models.PositiveIntegerField(default=1)),
                ('no_cadenas', models.PositiveIntegerField(default=1)),
                ('modulos_por_cadena', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inversor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dimensionamientos', to='core.inversor')),
                ('micro_inversor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dimensionamientos', to='core.microinversor')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionamiento', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Dimensionamiento',
                'verbose_name_plural': 'Dimensionamientos',
                'db_table': 'dimensionamiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
