# Generated by Django 4.2.27 on 2026-02-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inversor_microinversor_dimensionamiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensionamiento',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='dimensionamiento',
            name='inversor',
        ),
        migrations.RemoveField(
            model_name='dimensionamiento',
            name='micro_inversor',
        ),
        migrations.RemoveField(
            model_name='dimensionamiento',
            name='modulos_por_cadena',
        ),
        migrations.RemoveField(
            model_name='dimensionamiento',
            name='no_cadenas',
        ),
        migrations.CreateModel(
            name='DimensionamientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cadenas', models.PositiveIntegerField(default=1)),
                ('modulos_por_cadena', models.PositiveIntegerField(default=1)),
                ('indice', models.PositiveIntegerField(default=1)),
                ('dimensionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.dimensionamiento')),
                ('inversor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dimensionamiento_detalles', to='core.inversor')),
                ('micro_inversor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dimensionamiento_detalles', to='core.microinversor')),
            ],
            options={
                'db_table': 'dimensionamiento_detalle',
                'ordering': ['indice'],
            },
        ),
        migrations.AddConstraint(
            model_name='dimensionamientodetalle',
            constraint=models.UniqueConstraint(fields=('dimensionamiento', 'indice'), name='uniq_dim_indice'),
        ),
    ]
