# Generated by Django 4.2.27 on 2026-02-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dimensionamiento_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inversor',
            old_name='potencia_kw',
            new_name='potencia_w',
        ),
    ]
