# Generated by Django 4.2.27 on 2026-02-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_potencia_kw_inversor_potencia_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionamientodetalle',
            name='modulos_por_cadena_lista',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
