# Generated by Django 4.2.27 on 2026-02-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dimensionamientodetalle_modulos_por_cadena_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inversor',
            name='potencia_w',
        ),
        migrations.RemoveField(
            model_name='inversor',
            name='voltaje_salida',
        ),
        migrations.RemoveField(
            model_name='microinversor',
            name='canales',
        ),
        migrations.RemoveField(
            model_name='microinversor',
            name='potencia_w',
        ),
        migrations.AddField(
            model_name='inversor',
            name='corriente_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inversor',
            name='corriente_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inversor',
            name='no_fases',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inversor',
            name='no_mppt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inversor',
            name='potencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inversor',
            name='voltaje_arranque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inversor',
            name='voltaje_maximo_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inversor',
            name='voltaje_nominal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='microinversor',
            name='corriente_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='microinversor',
            name='corriente_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='microinversor',
            name='no_fases',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microinversor',
            name='no_mppt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microinversor',
            name='potencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='microinversor',
            name='voltaje_arranque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='microinversor',
            name='voltaje_maximo_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='microinversor',
            name='voltaje_nominal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
