# Generated by Django 4.2.27 on 2026-03-06 02:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_inversor_potencia_w_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.IntegerField(db_column='id_conductor', primary_key=True, serialize=False)),
                ('calibre_cable', models.CharField(db_column='calibre_cable', max_length=20)),
                ('tubo_1_2_pulgada', models.PositiveIntegerField(db_column='tubo_1/2_pulgada', default=0)),
                ('tubo_3_4_pulgada', models.PositiveIntegerField(db_column='tubo_3/4_pulgada', default=0)),
                ('tubo_1_pulgada', models.PositiveIntegerField(db_column='tubo_1_pulgada', default=0)),
                ('tubo_1_1_4_pulgada', models.PositiveIntegerField(db_column='tubo_1_1/4_pulgada', default=0)),
                ('tubo_1_1_2_pulgada', models.PositiveIntegerField(db_column='tubo_1_1/2_pulgada', default=0)),
                ('tubo_2_pulgada', models.PositiveIntegerField(db_column='tubo_2_pulgada', default=0)),
                ('tubo_2_1_2_pulgada', models.PositiveIntegerField(db_column='tubo_2_1/2_pulgada', default=0)),
            ],
            options={
                'db_table': 'conductores',
                'ordering': ['id_conductor'],
            },
        ),
        migrations.CreateModel(
            name='Condulet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ll', models.PositiveIntegerField(default=0)),
                ('tipo_lr', models.PositiveIntegerField(default=0)),
                ('tipo_lb', models.PositiveIntegerField(default=0)),
                ('tipo_t', models.PositiveIntegerField(default=0)),
                ('tipo_c', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'condulets',
            },
        ),
        migrations.CreateModel(
            name='ResultadoCalculoDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amperaje_fusible', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('total_de_cadenas', models.PositiveIntegerField(blank=True, null=True)),
                ('total_fusibles', models.PositiveIntegerField(blank=True, null=True)),
                ('metros_totales_cable', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('calibre_tuberia', models.CharField(blank=True, max_length=40, null=True)),
                ('total_tubos', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultado_calculo_dc',
            },
        ),
        migrations.CreateModel(
            name='CalculoDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(default=1)),
                ('metros_lineales', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('calibre_cable_solar', models.CharField(blank=True, max_length=20, null=True)),
                ('hilos_tuberia', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conductor', models.ForeignKey(blank=True, db_column='Id_conductores', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculos_dc', to='core.conductor')),
                ('condulet', models.OneToOneField(blank=True, db_column='Id_condulet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculo_dc', to='core.condulet')),
                ('dimensionamiento_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculos_dc', to='core.dimensionamientodetalle')),
                ('proyecto', models.ForeignKey(db_column='Id_Proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='calculos_dc', to='core.proyecto')),
                ('resultado_dc', models.OneToOneField(blank=True, db_column='Id_resultadoo_dc', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculo_dc', to='core.resultadocalculodc')),
            ],
            options={
                'db_table': 'calculo_dc',
                'ordering': ['proyecto_id', 'indice'],
            },
        ),
        migrations.AddConstraint(
            model_name='calculodc',
            constraint=models.UniqueConstraint(fields=('proyecto', 'indice'), name='uniq_calculo_dc_proyecto_indice'),
        ),
    ]
