# Generated by Django 4.2.27 on 2026-03-07 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_conductor_condulet_resultadocalculodc_calculodc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCalculoAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amperaje_proteccion', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('total_de_cadenas_ac', models.PositiveIntegerField(blank=True, null=True)),
                ('total_protecciones', models.PositiveIntegerField(blank=True, null=True)),
                ('metros_totales_cable_ac', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('calibre_tuberia_ac', models.CharField(blank=True, max_length=40, null=True)),
                ('total_tubos_ac', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultado_calculo_ac',
            },
        ),
        migrations.CreateModel(
            name='CalculoAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(default=1)),
                ('metros_lineales_ac', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('calibre_cable_thhw', models.CharField(blank=True, max_length=20, null=True)),
                ('hilos_tuberia_ac', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conductor', models.ForeignKey(blank=True, db_column='Id_conductores', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculos_ac', to='core.conductor')),
                ('condulet', models.OneToOneField(blank=True, db_column='Id_condulet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculo_ac', to='core.condulet')),
                ('dimensionamiento_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculos_ac', to='core.dimensionamientodetalle')),
                ('proyecto', models.ForeignKey(db_column='Id_Proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='calculos_ac', to='core.proyecto')),
                ('resultado_ac', models.OneToOneField(blank=True, db_column='Id_resultadoo_ac', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculo_ac', to='core.resultadocalculoac')),
            ],
            options={
                'db_table': 'calculo_ac',
                'ordering': ['proyecto_id', 'indice'],
            },
        ),
        migrations.AddConstraint(
            model_name='calculoac',
            constraint=models.UniqueConstraint(fields=('proyecto', 'indice'), name='uniq_calculo_ac_proyecto_indice'),
        ),
    ]
