# Generated by Django 4.2.27 on 2026-03-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_resultadocalculoac_calculoac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaConductoresAWGConReactancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibre_awg', models.PositiveIntegerField(unique=True)),
                ('area_transversal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('resistencia_cc', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('resistencia_ca', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('reactancia', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Conductor AWG con reactancia',
                'verbose_name_plural': 'Conductores AWG con reactancia',
                'db_table': 'tabla_conductores_awg_con_reactancia',
                'ordering': ['calibre_awg'],
            },
        ),
    ]
