# Generated by Django 4.2.27 on 2026-03-08 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tablaconductoresawgconreactancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoTension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje_tension_ac', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('porcentaje_voltaje_tension_ac', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('voltaje_tension_dc', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('porcentaje_voltaje_tension_dc', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('calculo_rt_ac', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('calculo_rt_dc', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('corriente_corregida', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'resultado_tension',
            },
        ),
        migrations.CreateModel(
            name='CalculoTension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(default=1)),
                ('serie', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_calculo', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], default='AC', max_length=2)),
                ('tipo_cable_ac', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_cable_dc', models.CharField(blank=True, default='', max_length=20)),
                ('factor_potencia_ac', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('factor_potencia_dc', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('temperatura_ac', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('temperatura_dc', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('longitud_ac', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('longitud_dc', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(db_column='ID_Proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='calculos_tension', to='core.proyecto')),
                ('resultado_tension', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculo_tension', to='core.resultadotension')),
                ('tension_ac', models.ForeignKey(blank=True, db_column='ID_tension_AC', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculos_tension_ac', to='core.calculoac')),
                ('tension_dc', models.ForeignKey(blank=True, db_column='ID_tension_DC', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculos_tension_dc', to='core.calculodc')),
            ],
            options={
                'db_table': 'calculo_tension',
                'ordering': ['proyecto_id', 'indice', 'tipo_calculo', 'serie'],
            },
        ),
        migrations.AddConstraint(
            model_name='calculotension',
            constraint=models.UniqueConstraint(fields=('proyecto', 'indice', 'tipo_calculo', 'serie'), name='uniq_calculo_tension_proyecto_indice_tipo_serie'),
        ),
    ]
