# Generated by Django 4.2.27 on 2026-03-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_resultadotension_calculotension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculodc',
            name='metros_lineales_por_serie',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
