# Generated by Django 4.2.27 on 2026-03-10 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_calculodc_metros_lineales_por_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosarioConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField()),
                ('formula', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Concepto del glosario',
                'verbose_name_plural': 'Conceptos del glosario',
                'db_table': 'glosario_conceptos',
                'ordering': ['nombre_concepto'],
            },
        ),
    ]
