# Generated by Django 4.2.27 on 2026-03-10 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_glosarioconcepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaNOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tabla', models.CharField(max_length=200, unique=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('nombre_imagen', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tabla NOM',
                'verbose_name_plural': 'Tablas NOM',
                'db_table': 'tablas_nom',
                'ordering': ['nombre_tabla'],
            },
        ),
    ]
