# Generated by Django 4.2.27 on 2026-03-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tablanom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablanom',
            name='nombre_imagen',
        ),
        migrations.AddField(
            model_name='tablanom',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tablas_nom/'),
        ),
    ]
