# Generated by Django 4.2.27 on 2026-03-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_tablanom_nombre_imagen_tablanom_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablanom',
            name='nombre_tabla',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
